### ISSUE TITLE
Human-readable TXT record format

### ISSUE THREAD

**Issue by frolic** [holic/redirect.name#1]
[This RFC](http://www.ietf.org/rfc/rfc1464.txt) describes `TXT` records with the following format:

```
<owner> <class> <ttl> TXT "<attribute name>=<attribute value>"
```

This is how I decided to go with `redirect.name=...` for the `TXT` record format for this service. However, I'm seeing some services not following the RFC, specifically DNSimple's `ALIAS` record, which adds a `TXT` record with value  `ALIAS for alias.redirect.name`.

If it's not really necessary to follow this RFC, maybe a more generic, human readable format would be ideal? Something like:
- `Redirects to https://github.com/holic`
- `Redirects permanently to https://github.com/holic`
- `Redirects from /github to https://github.com/holic/redirect.name`
- `Redirects permanently from /* to https://github.com/holic/*`

**Comment by Crelloc** [comment]
Just what I was looking for! Thanks
