### ISSUE TITLE
Can't get the redirect to work

### ISSUE THREAD

**Issue by booyaa** [holic/redirect.name#21]
Trying to work out what I got wrong with the instructions on redirect.name:

Here's how I set up my redirect in CloudFlare:

![screen shot 2017-07-15 at 10 21 53](https://user-images.githubusercontent.com/192864/28238259-b0178cc6-6947-11e7-8f21-edd6f432b03a.png)

Here's a exported file from CloudFlare
```
;; TXT Records
_redirect.booyaa.booyaa.wtf.    300     IN      TXT     "Redirects to http://booyaa.org"

;; CNAME Records
booyaa.booyaa.wtf.      300     IN      CNAME   alias.redirect.name.
```

**Comment by holic** [comment]
It looks like your redirect is set up correctly:
http://booyaa.booyaa.wtf

Did you mean to set this up on the root record? If so, you'll need the CNAME record to be on the root (`@`) and the TXT record on `_redirect`.
