### ISSUE TITLE
where can I donate?

### ISSUE THREAD

**Issue by mrexodia** [holic/redirect.name#22]
I love this service and I wouldn't mind donating (BTC or otherwise) a little to keep the servers running...

**Comment by holic** [comment]
Thanks so much for the kind offer! I'd really appreciate it if you could send the donation by way of the EFF: https://supporters.eff.org/donate/donate

**Comment by mrexodia** [comment]
Sorry for the late response, but I did donate some coins to the EFF and thanks again for your service!

**Comment by holic** [comment]
🙏
